language: rust
sudo: false
rust:
  - 1.15.0
  - 1.26.0 # i128 feature
  - 1.32.0 # Rust 2018 / rand feature
  - stable
  - beta
  - nightly
script:
  - ./ci/test_full.sh
matrix:
  include:
    # try a target that doesn't have std at all
    - name: "no_std"
      rust: stable
      env: TARGET=thumbv6m-none-eabi
      before_script:
        - rustup target add $TARGET
      script:
        - cargo build --verbose --target $TARGET --no-default-features --features i128,rand,serde
    - name: "rustfmt"
      rust: 1.31.0
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check
